- stat:
    path: /etc/init.d/orientdb
  register: service_orientdb_stat

- name: Install orientdb as a service
  command: 'cp {{orientdb_path}}/bin/orientdb.sh /etc/init.d/orientdb'
  when: service_orientdb_stat.stat.exists == False or orientdb_force_install == True

- name: Launch orientdb service
  service:
    name=orientdb
    state=started
    enabled=yes
  when: service_orientdb_stat.stat.exists == False or orientdb_force_install == True
