- stat:
    path: /etc/init.d/orientdb
  register: service_sysvinit_stat
  when: "{{ ansible_distribution_version|int <= 14 }}"

- name: Install orientdb as a sysvinit service
  copy:
    remote_src: True
    src: "{{ orientdb_path }}/bin/orientdb.sh"
    dest: /etc/init.d/orientdb
    mode: a+x
  register: orientdb_sysvinit_unit
  when: "{{ ansible_distribution_version|int <= 14 }} and (service_sysvinit_stat.stat.exists == False or orientdb_force_install == True)"

- name: Install orientdb as a systemd service
  template:
    src: orientdb.service.j2
    dest: /etc/systemd/system/orientdb.service
    owner: root
    group: root
    mode: 400
  register: orientdb_systemd_unit
  when: "{{ ansible_distribution_version|int > 14 }} or orientdb_force_install == True"

- name: systemctl daemon-reload
  command: systemctl daemon-reload
  when: "{{ ansible_distribution_version|int > 14 }} and orientdb_sysvinit_unit|changed"

- name: Launch orientdb service
  service:
    name: orientdb
    state: restarted
    enabled: yes
  when: (orientdb_sysvinit_unit is defined and orientdb_sysvinit_unit|changed) or (orientdb_systemd_unit and orientdb_systemd_unit|changed) or orientdb_force_install == True
